---
version: 2
jobs:
  lint:
    docker:
    - image: circleci/ruby:2.4.2
      environment:
        BUNDLE_PATH: vendor/bundle
        RAILS_ENV: test
    steps:
    - checkout
    - restore_cache:
       keys:
         - deps-{{ checksum "Gemfile.lock" }}
         - deps-
    - run:
        name: Bundle Install
        command: bundle check || bundle install
    - save_cache:
        key: deps-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
    - run:
        name: Run Rubocop
        command: bundle exec rubocop
  test:
    docker:
    - image: circleci/ruby:2.4.2
      environment:
        BUNDLE_PATH: vendor/bundle
        RAILS_ENV: test
    steps:
    - checkout
    - restore_cache:
       keys:
         - deps-{{ checksum "Gemfile.lock" }}
         - deps-
    - run:
        name: Bundle Install
        command: bundle check || bundle install
    - save_cache:
        key: deps-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
    - run:
        name: Run tests
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out test_results/rspec.xml \
                            --format progress
    - store_test_results:
        path: test_results
  deploy:
    docker:
    - image: circleci/ruby:2.4.2
    steps:
    - checkout
    - run:
        name: Run Heroku Setup Script
        command: bash .circleci/setup_heroku.sh
    - run:
        name: Deploy to Heroku
        command: |
          heroku git:remote -a fizzbuzzsophia
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/fizzbuzzsophia.git HEAD:refs/heads/master
          sleep 5
          heroku restart
workflows:
  version: 2
  all:
    jobs:
    - deploy:
        context: heroku
        branches:
          only: "master"
        requires:
        - lint
        - test
    - lint:
        context: heroku
    - test:
        context: heroku
