development:
  adapter: postgresql
  encoding: unicode
  database: fizzbuzzsophia_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: fizzbuzzsophia_test
  pool: 5

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
